### ISSUE TITLE
Widget resize

### ISSUE THREAD

**Issue by Abribus** [taboola/taboola-android#7]
The widget is not properly resized if the orientation switches from portrait to landscape then to portrait again (see your own example "Taboola sample" to verify it).
More precisely, the widget is not resized at all when the orientation changes from landscape to portrait.

**Comment by omriariav** [comment]
@Abribus This Github repo is no longer maintained. Sorry for the delay in answering your question. Since posting your question we improved the way we're returning the widget size after orientation change. You can see this improvement by upgrading to the latest SDK version. See more information here: https://sdk.taboola.com
